### PR TITLE
Does not accept failed jobs if less then 10 pods failed (#21)

### PR DESCRIPTION
**Pull request by robinvandenbogaard**

### CODE REVIEW

**Review by briceruzand — APPROVED** [review]
LGTM

**Comment by carterqw2** [comment]
@groundnuty any chance to get this merged?

**Comment by groundnuty** [comment]
yep, I will get to it this month - just waiting for some free time

**Comment by mfinelli** [comment]
For anyone else (like me) waiting for this to get merged/released I have done so and published here: https://hub.docker.com/r/mfinelli/k8s-wait-for. It's not versioned (latest only) because I don't plan on maintaining it after this PR gets merged and released here.

I can also confirm that it does fix the problem

**Comment by zhming0** [comment]
🙏 🙏  It would be great if this PR can be merged. It's a critical bug fix.

**Comment by takaczapka** [comment]
I found this bug, and hey, it's fixed! Not merged tho :(. Any chance of merging it in?

**Comment by groundnuty** [comment]
Merged. Apologies for the long wait!

**Pull request merged**
